pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                echo 'Compiling the java source code123'
                sh 'javac Hello.java'
            }
        }
        stage('run') {
            steps {
                echo 'Running the compiled java code.123'
                sh 'java Hello'
            }
        }
    }
}